apiVersion: v1
kind: Pod 
metadata:
  name:
    newsreader-pod
  labels:
    app: newsreader
spec:
  containers:
  - name: newsreader
    image: docker.io/rlkamradt/newsreader:latest
    ports:
    - containerPort: 8080
    env:
      - name: MONGO_USER
        valueFrom:
          secretKeyRef:
            name: mongo-secret
            key: username
      - name: MONGO_PASS
        valueFrom:
          secretKeyRef:
            name: mongo-secret
            key: password
      - name: NEWSAPI_KEY
        valueFrom:
          secretKeyRef:
            name: newsapi-key
            key: key
      - name: MONGO_SERVER
        value: mongodb-0.mongodb 
