apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: readnews-ingress
  annotations:
    cert-manager.io/issuer: ca-issuer 
spec:
  rules:
  - host: readnews.local
    http:
      paths:
      - backend:
          serviceName: readnews-service
          servicePort: 8080
        path: /
  - host: readnewsblock.local
    http:
      paths:
      - backend:
          serviceName: readnewsblock-service
          servicePort: 8080
        path: /
  - host: readnewsgo.local
    http:
      paths:
      - backend:
          serviceName: readnewsgo-service
          servicePort: 8080
        path: /
  tls:
  - hosts:
    - readnewsblock.local
    secretName: readnewsblock-cert
  - hosts:
    - readnewsgo.local
    secretName: readnewsgo-cert
  - hosts:
    - readnews.local
    secretName: readnews-cert
